name: Publisher
on: push
jobs:
  build-apk:
    if: "startsWith(github.event.commits[0].message, '[publish]')"

    # Name the Job
    name: Publish
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.6'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build ios --release
      - uses: actions/upload-artifact@v1
        with:
          # Name of the command/step.
          name: release-apk
          # Path to the release apk.
          path: build/app/outputs/apk/release/app-release.apk